### ISSUE TITLE
[feat] Interview view 작업

### ISSUE THREAD

**Issue by snowedev** [Find-U-I/Find-iOS#6]
## 💡 Issue
Interview view 작업합니다.

## 📝 todo
- [x] Interview 세그 작업
- [x] Interview textView 작업
- [x] 사진 추가 기능 구현
- [x] 저장 버튼 로직
- [x] Interview 18개 질문 중에 응답한거 %화
